### ISSUE TITLE
Unable to sync with saber cloud

### ISSUE THREAD

**Issue by JustDj-Git** [saber-notes/saber#1304]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Unable to sync with saber cloud. I tried to:
-create a new acc
-change devices (tried on Samsung tab s9, tab s6, nothing phone 1 and 2, appimage and flatpak versions on Linux
-reinstall saber everywhere

sometimes files are synced with cloud (I can see them in cloud) but if I delete notes from my pad/phone - I cant resync them

Error on Linux (flatpak):
`flutter: WARNING: SaberSyncInterface: Failed to get sync file from remote file: Exception: Decryption failed for Saber/
`
`flutter: WARNING: SaberSyncInterface: Failed to get sync file from remote file: Invalid argument(s): Invalid or corrupted pad block`

### To reproduce

1. Sign-in on tab + phone (or more devices)
2. Create any note and sync
3. Try to sync notes on other devices - nothing happens 

### Expected behavior

Sync :)

### Saber version

v0.24.1

### Device

- Devices: Linux PC, Samsung s9 tab, Samsung tab s6, nothing phone 1 and 2
- OS: Debian, Arch, OpenSUSE, Fedora, Android

**Comment by TekkertheChaot** [comment]
same here! have the same bahaviour using the flatpack 0.24.1 on linux and 0.24.1 on android. 
I also saw the same journal entry described above.

I've attached a video reproducing this behavior
https://github.com/saber-notes/saber/assets/17234581/10b83ebd-3871-45e2-804c-d9931bc8bb7a

**Comment by gewinh** [comment]
Same here Saber v0.24.1 syncs to the nextcloud server with what looks like the right file size, but there is no syncing between my Android devices. I have a phone and a tablet each has the same version of saber and each is setup to sync to the same Nextcloud account with the same encryption password. They both sync there files to the saber folder but files created on the phone don't show up on the tablet and viz versa. I have also installed Saber on ubuntu as a snap and have the same issue, no syncing between devices. I am running Nextcloud 29.02 behind an nginx reverse proxy. Other apps that are using nextcloud sync are working fine. eg. Moonreader, files, notes deck etc.

While we are at it although I love the Saber software, I don't like the app lock in, by forcing encryption when you sync to Nextcloud (this should be optional). If for some reason Saber goes away or stops working, I would need to get to my notes another way. There are plenty of encryption options external from Saber that a user could choose, if they decided they needed that level of security.   Thanks again for the great work

**Comment by TekkertheChaot** [comment]
@gewinh 
Regarding the encryption, I absolutely support you on that! This should be an option for the user to decide.
The enabled encryption could be a default recommendation, which can be disabled on setup behind a "_I know what I'm doing_" button. 
Please create a separate, trackable issue for this as this issue #1304 should only be tracking the sync issue. ;)

**Comment by Lennart01** [comment]
This issue was introduced after 0.23.0.
I can get syncing to work flawlessly between my android devices on that version.

**Comment by mar565** [comment]
> This issue was introduced after 0.23.0. I can get syncing to work flawlessly between my android devices on that version.

Thank you for the fix. Can confirm this issue on 24.0.1 FOSS version.

**Comment by ceskyDJ** [comment]
> While we are at it although I love the Saber software, I don't like the app lock in, by forcing encryption when you sync to Nextcloud (this should be optional). If for some reason Saber goes away or stops working, I would need to get to my notes another way. There are plenty of encryption options external from Saber that a user could choose, if they decided they needed that level of security. Thanks again for the great work

The "App lock in" isn't actually that bad. You can freely export your notes (to PDF or SBA), if you want to. I think it's good enough for the use-case you described. But, as @TekkertheChaot said, don't mix up two things in one issue, please. If you want to discuss this a bit more, create a new issue/discussion for it.

**Comment by charitarthchugh** [comment]
Just curious, has this been fixed with v0.24.2?

**Comment by QubaB** [comment]
Syncing was rewritten in 0.24.0

**Comment by TekkertheChaot** [comment]
> Syncing was rewritten in 0.24.0

Yeah but the issue persists in 0.24.1 so this needs attention

**Comment by QubaB** [comment]
see #1314

**Comment by adil192** [comment]
That message is expected behaviour, it's just because `Saber/` is a folder and not a file

**Comment by TekkertheChaot** [comment]
> That message is expected behaviour, it's just because `Saber/` is a folder and not a file

Hmm, alright. Either way, I can't seem to sync notes between devices. 
So this message probably doesn't relate to the sync issue?

**Comment by JustDj-Git** [comment]
The problem still persists - can't sync between devices...

**Comment by bryanpaget** [comment]
I also am unable to sync between devices.

**Comment by TekkertheChaot** [comment]
@adil192, sorry to ping you like this but (as other people are also pointing out) this issue still persists.
Can you reopen, please?

**Comment by bryanpaget** [comment]
I have four devices connected to a self-hosted nextcloud instance. All four devices, a ThinkPad running Ubuntu, Steam Deck, Samsung phone, Samsung tablet, and all connect to the server, and all think they are syncing. But I have four separate sets of synced files. It's like the devices sync to the server in their own isolated storage compartments.

**Comment by TekkertheChaot** [comment]
I have opened a new issue #1326 in hopes to avoid it being overlooked. 
Hopefully someone of the moderators / contributors can sort this out. 

_(I know this is dirty and not the intended way of handling / against the CoC, but I'm trying to keep this on the radar as long as I cannot contribute myself to the project ❤️)_

**Comment by TekkertheChaot** [comment]
For anyone still having this issue and monitoring this thread, it seems this issue is being tracked by #1320 .
